language: python
python:
- '3.6'
script:
- python init_data_sample.py
- pytest tests
deploy:
  provider: pypi
  user: foolcage
  password:
    secure: MvVCnUZUuTYxzs8R8kWTocOqZt2MGUX/W1hdKMxKJ9G9hFOYhzjEnbsF1Sc9yHB/0S1OY49068ScbN6iCuyKK2LZy/x3o7cKJgPnQt2LEjy6Yuu9MLxT6v8hJ0MTT3YCn0N8bNv4tOz7KkxxbZ8O/b5MgIKfdjBhVHEj92hhykYzyzlmG8mF+nxU/j0IGCAdxN9+IDioMIvCgnFqQhvkDwva4YbG6Uy+8YMVHFT3I+tSZRSmYxl/IwHJS+5tinI4TxX/ewrI5EznOe0HZvhF+eez+tGenS3pKF4hqF6t4RmKQX2kkdMuPFAvuveoMnPGiaSdoEMni1JPFnZL+3R4GVJPzk4F10v6AZPd10CARXqEwP23JCKAe0WvnbSBkV4iKpkvgxqPA59UwNQ90Jn4pDcTSao1WfRliAnBWCVj7S4x6xjEoNKPvOhXP3RPIYhgEFu4Ma4Cpihkof6VVtlg8VAJKH7j1vWmms3ShdddKXMeF2365sn5Owe671okYmMYMas/v47Y2Cz/0hwpVLuklNR5OYayXMXfUMIG2pH1pEFvg7y8v7ivy1EyCKGva+M/qEnoR1VGWNGSkypJHxG+w8dbtYwf3EYTA9fk/di3ygzepV7RrKJSDf8R+NwFrSfXeoEP07LonbtGN9iIz7Lp5PoB6rv99NHihlB47n1+PtM=
  on:
    tags: true
notifications:
  email:
    recipients:
    - 5533061@qq.com
env:
  matrix:
  - secure: EoHmeyp0IpmBEzQL/TPeTopwVGpCZunEm6jgA8N37RUQ+5+W4gX2W/7ILdoCHHv7m0+LI2CV3DciHqOz4aqDj0ooxJQWazqLPStk5MOISDhhjg2p78v+tug7KjL7WFwbMnvhxstu4kr2b3/0by4fSLc/b+LMF5DQXsMehW9JCYthFNlcj+avYavzec8xT4ZTgidnvc02PFWHMjK1lnzUL9VCbgexpoKFBtPFXRXXFok/OtLZETWgh3PSy+CcAz+CRl5jBmYKg5V8tlhUUW8af0HmKM/yHGIw4wyl0Gmd9slUdE0V71X+5aDulEcr+LfSZXfhyQYbxtfefqJqJMy57tzpLT6g4GpVCFp4kHPz068Z+gJiC+qITp41VObwWLoFOZrHIXdW7J2v8FlItjrCToieDNx+3PBwQyel7ibqa2KdDfGBJS3JQWo+3b4COs6eaQ+3xpeclKsfIXy1olV4xeN5LR1/EXRngPUlVfqLJyg8ZS38xj3T0JrzYNHTGlQlSd9m3Wv4FK0EFfYBI4guWwnvLtPHRWlumteYBqhHeZQnZFLnlgFT40LHjsKlWoS0mT3YDIurhTkY97yXGxkcQdQ0PzhAjBLOZblp35ZBTT0veGHvRv9iajJ45sbrApj6mRxPVX/QCRmo6xDQLAZZYHiS8IzB28dGVxSlubJ8FAo=
  - secure: sDePou56VfY/WH0d0zuE40V4WKXgMW1Pyzcv9EwGIUL055oJedi56AVg4zkoXaDJkVsKna7MiW9nBg1/0oMFwG5/lNi0p1i1MKmskWsDeeJfjHIKEfGn6a4yjwMfg5RFpPi/2AA4J9qG8gqK/qeGyQ1WLZVKhBlW/KrCVZRRgEpxP6R8MbWcpOJzHGfA8bFerv4Nhin/Wnb4pkGgUx+eW3wTwZwDq7hx77rfeZ0ADEwakLnb9dOVqfENDUaKP9wPL90KV5ldC9uRvjXEFtqy1IsA43fJ9a6B1UBqAqJ/vD45epba6PZcKz5O8AhWahYaX/kEHOA0a3tFDmwOqwNuyl0gHKSrnBct2k+v3n3AiwHsT4wOL4VG4WTbwYETo7wwE6JG4mR+WNh/sk6wybyVGOdym8n18Ooqi2bn6vCWUyOb1O0KSD01kZPKhuiBMThLhyixRqfKntFKmD4fSW1keoNM0s382Nn7eHQQfIu5AJhThcUQZ4CpAj7vx+yD+5wUkILbtUGm5boLWJcM/Qs5KUmVWYTfowk4cJypyzANNlek3o2DTAgPRDAnAMufDFmZG0tDqDBBZ6yE/CBlR5Ola9DcbMuC7C5hrIdi+W64l+5cXxbsII5Cy9adZzKKd8rWp1BTE4nIxjd6ZObasRtC0K7a01brdL7PZBC5o0r+XQE=
